language: python
python:
    - '3.4'
    - '3.5'
    - '3.6'
branches:
    only:
        - master
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python3-matplotlib python3-scipy pyton3-docopt
script: python -m unittest

